version: '3.4'

services:

  zipkin-server: 
    container_name: Zipkin_Tracing_Server
    image: openzipkin/zipkin:2.23.2
    ports:
      - 9411:9411
    restart: always
    depends_on: 
      - rabbit-mq
    environment: 
      RABBIT_URI: amqp://guest:guest@rabbit-mq:5672
    networks:
      - jeremias-network
  
  rabbit-mq: 
    container_name: RabbitMQ
    image: rabbitmq:3.8.14-management
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - jeremias-network

  cambio-db: 
    container_name: Cambio_DB
    image: mysql:5.7.22
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment: 
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: Test123
      MYSQL_USER: docker
      MYSQL_PASSWORD: Test123
      MYSQL_DATABASE: cambio_service
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3308
    ports:
      - 3308:3308
    expose: 
      - 3308
    networks:
      - jeremias-network

  book-db: 
    container_name: Book_DB
    image: mysql:5.7.22
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment: 
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: Test123
      MYSQL_USER: docker
      MYSQL_PASSWORD: Test123
      MYSQL_DATABASE: book_service
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3310
    ports:
      - 3310:3310
    expose: 
      - 3310
    networks:
      - jeremias-network

  naming-server: 
    container_name: Service_Discovery
    image: jeremiasrg/naming-server:0.0.1-SNAPSHOT
    ports:
      - 8761:8761
    depends_on: 
      - rabbit-mq
    networks:
      - jeremias-network
  
  api-gateway: 
    container_name: API_Gateway
    image: jeremiasrg/api-gateway:0.0.1-SNAPSHOT
    ports:
      - 8765:8765
    depends_on: 
      - naming-server
      - rabbit-mq
    environment: 
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
      RABBIT_URI: amqp://guest:guest@rabbit-mq:5672
      SPRING_RABBITMQ_HOST: rabbit-mq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit
    networks:
      - jeremias-network

  cambio-service: 
    container_name: Cambio_Service
    image: jeremiasrg/cambio-service:0.0.1-SNAPSHOT
    ports:
      - 8002:8000
    depends_on: 
      - naming-server
      - cambio-db
      - rabbit-mq
    environment: 
      TZ: America/Sao_Paulo
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
      SPRING.DATASOURCE.URL: jdbc:mysql://cambio-db:3308/cambio_service?useSSL=false&serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
      SPRING.DATASOURCE.USERNAME: docker 
      SPRING.DATASOURCE.PASSWORD: Test123
      SPRING.FLYWAY.URL: jdbc:mysql://cambio-db:3308/cambio_service?useSSL=false&serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
      SPRING.FLYWAY.USER: docker
      SPRING.FLYWAY.PASSWORD: Test123
      RABBIT_URI: amqp://guest:guest@rabbit-mq:5672
      SPRING_RABBITMQ_HOST: rabbit-mq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit
    networks:
      - jeremias-network

  book-service: 
    container_name: Book_Service
    image: jeremiasrg/book-service:0.0.1-SNAPSHOT
    ports:
      - 8100:8100
    depends_on: 
      - naming-server
      - book-db
      - rabbit-mq
    environment: 
      TZ: America/Sao_Paulo
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
      SPRING.DATASOURCE.URL: jdbc:mysql://book-db:3310/book_service?useSSL=false&serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
      SPRING.DATASOURCE.USERNAME: docker 
      SPRING.DATASOURCE.PASSWORD: Test123
      SPRING.FLYWAY.URL: jdbc:mysql://book-db:3310/book_service?useSSL=false&serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
      SPRING.FLYWAY.USER: docker
      SPRING.FLYWAY.PASSWORD: Test123
      RABBIT_URI: amqp://guest:guest@rabbit-mq:5672
      SPRING_RABBITMQ_HOST: rabbit-mq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit
    networks:
      - jeremias-network

networks: 
  jeremias-network:
    driver: bridge
