server:
  port: 8100
eureka:  client:    service-url:      defaultZone: http://localhost:8761/eureka
resilience4j:
  bulkhead:    instances:      my-bulkhed-config-name:
        max-concurrent-calls: 10
  ratelimiter:    instances:      my-config-name:
        limit-for-period: 2
        limit-refresh-period: 10s  retry:    instances:      my-config-1:
        max-attempts: 3
      my-config-2:
        max-attempts: 7
      my-config-3:
        max-attempts: 10
        wait-duration: 2s
        enable-exponential-backoff: true
spring:  application:    name: book-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/book_service?useTimezone=true&serverTimezone=UTC
    username: root
  jackson:
    default-property-inclusion: NON_NULL    serialization:      fail-on-empty-beans: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
  flyway:
    url: jdbc:mysql://localhost:3306/book_service?useTimezone=true&serverTimezone=UTC
    user: root
  sleuth:    sampler:      probability: 1.0 #100%
  zipkin:
    base-url: http://localhost:9411/
springdoc:
  show-actuator: true  api-docs:    path: book-service/v3/api-docs 